### PR TITLE
Br isilonqe 977

### PR DESCRIPTION
**Pull request by isi-adas**
Refer comments in https://github.com/emc-isilon/pike/pull/80.

Testing:

[TestResults.txt](https://github.com/emc-isilon/pike/files/4801340/TestResults.txt)

### CODE REVIEW

**Comment by isi-adas** [comment]
cc: @isi-mfurer

**Comment by isi-mfurer** [comment]
1 actions failure

```
======================================================================
FAIL: test_qfid_same_file_seq_delete (queryondiskid.TestQueryOnDiskID)
Opening the same file name after deleting the first file should return
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pike/pike/pike/test/queryondiskid.py", line 221, in test_qfid_same_file_seq_delete
    "Subsequent open after delete returns same file id")
AssertionError: array('B', [108, 110, 200, 244, 35, 248, 186, 151, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == array('B', [108, 110, 200, 244, 35, 248, 186, 151, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) : Subsequent open after delete returns same file id
```

This occurs periodically, i think it's a samba issue.

**Comment by isi-mfurer** [comment]
@isi-adas can you requeue this job and make sure it's passing https://github.com/isi-adas/pike/runs/786072766?check_suite_focus=true

**Comment by isi-adas** [comment]
> 1 actions failure
> 
> ```
> ======================================================================
> FAIL: test_qfid_same_file_seq_delete (queryondiskid.TestQueryOnDiskID)
> Opening the same file name after deleting the first file should return
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/runner/work/pike/pike/pike/test/queryondiskid.py", line 221, in test_qfid_same_file_seq_delete
>     "Subsequent open after delete returns same file id")
> AssertionError: array('B', [108, 110, 200, 244, 35, 248, 186, 151, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == array('B', [108, 110, 200, 244, 35, 248, 186, 151, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) : Subsequent open after delete returns same file id
> ```
> 
> This occurs periodically, i think it's a samba issue.

Yeah, I looked into the error. This seems to be a samba issue, not an issue with pike or fix. Well the reruns passed here
https://github.com/isi-adas/pike/runs/790130913?check_suite_focus=true

**Pull request merged**
