### PR TITLE
Blackify source pike/*.py

### PR DESCRIPTION
**Pull request by jtmoon79**
black -l 88 pike/*.py

### CODE REVIEW

**Comment by isi-adas** [comment]
Looks like CI fails. I think we can reformat but will this let python 2.7 pass? Well, 3.7 and others also fail. Any reasons?

**Comment by isi-mfurer** [comment]
Looks like the CI failures are a result of changes to the samba image that we're depending on... need to dig in locally and fix the workflow file (and strictly pin it to a dperson/samba version)

**Comment by isi-mfurer** [comment]
https://github.com/emc-isilon/pike/blob/master/.github/workflows/test_samba.yml#L20

@jtmoon79 in the meantime, you can change the workflow file to reference the last known good image and see if that works: `dperson/samba:197dd6dac98274109c9c9c024f2bb1ebe2e075fa1ab901640a8fe94e875007d1`

**Comment by isi-mfurer** [comment]
please rebase on `master` to pull in my fix for the samba CI test

**Comment by jtmoon79** [comment]
Last failure
```
pike/test/compound.py::CompoundTest::test_create_failed_and_query 
-------------------------------- live log call ---------------------------------
...
DEBUG    pike:model.py:875 send (127.0.0.1/60042 -> 127.0.0.1/49153): CreateRequest create_query_failed, QueryDirectoryRequest FILE_DIRECTORY_INFORMATION
DEBUG    pike:model.py:915 recv (127.0.0.1/49153 -> 127.0.0.1/60042): ErrorResponse SMB2_CREATE STATUS_OBJECT_NAME_COLLISION, ErrorResponse SMB2_QUERY_DIRECTORY STATUS_FILE_CLOSED
...
E   AssertionError: "STATUS_FILE_CLOSED" raised when "STATUS_OBJECT_NAME_COLLISION" expected
```
https://github.com/emc-isilon/pike/pull/101/checks?check_run_id=1883893565#step:9:461

**Review by isi-mfurer — APPROVED** [review]
nothing too controversial

**Pull request merged**
