### PR TITLE
Use getaddrinfo to resolve the supplied server address. This means it's ...

### PR DESCRIPTION
**Pull request by bobdoah**
...possible to use an IPv4 or IPv6 address.

### CODE REVIEW

**Comment by isi-mfurer** [comment]
Rejecting this pull request to take one which uses symbolic variable names

**Comment by bobdoah** [comment]
That'd be this commit - https://github.com/isi-mfurer/pike/commit/d52a21c8b7933f7650959239cac4ece930ec65de

**Comment by isi-mfurer** [comment]
https://github.com/isi-mfurer/pike/commit/9887b1c4a287c8fba03831937545975a14f31e06

**Comment by isi-mfurer** [comment]
https://github.com/emc-isilon/pike/pull/8

**Pull request closed without merging**
